default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: dika1708
  host: localhost

development:
  <<: *default
  database: rails_crud_development

test:
  <<: *default
  database: rails_crud_test

production:
  <<: *default
  database: rails_crud_production
